package:
  name: cassandra-5.0
  version: 5.0.0
  epoch: 0
  description: Open Source NoSQL Database
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python-3.11 # needed for cqlsh
    provides:
      - cassandra=${{package.full-version}}

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+\.\d+)\.\d+$
    replace: "$1"
    to: major-minor-version


environment:
  contents:
    packages:
      - ant
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - cython
      - py3-supported-cython
      - py3-supported-pip
      - openjdk-11-default-jvm
      - py3-setuptools
      - python3
      - python3-dev

  environment:
    JAVA_HOME: /usr/lib/jvm/java-11-openjdk
    CASSANDRA_USE_JDK11: true

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/apache/cassandra
      expected-commit: 186272edca920c757b91bf95c2392bafa1a38d72
      tag: cassandra-${{package.version}}

  - runs: |
      set -x
      cython --help
      ant artifacts -Dversion=${{package.version}}

      # Install cassandra from the tarball in build/dist into the destdir in /usr/share/java/cassandra
      mkdir -p "${{targets.destdir}}"/usr/share/java/cassandra
      tar --strip-components 1 -C "${{targets.destdir}}"/usr/share/java/cassandra -xzf build/apache-cassandra-${{package.version}}-bin.tar.gz

      # Symlink everything in the cassandra bin directory into /usr/bin
      mkdir -p "${{targets.destdir}}"/usr/bin/

      for f in /home/build/build/dist/bin/*; do
        filename=$(basename "$f")
        ln -sf  /usr/share/java/cassandra/bin/"$filename" "${{targets.destdir}}"/usr/bin/"$filename"
      done

      mkdir -p ${{targets.destdir}}/var/lib/cassandra
      mkdir -p ${{targets.destdir}}/var/log/cassandra

      ln -sT /var/lib/cassandra/ "${{targets.destdir}}"/usr/share/java/cassandra/data
      ln -sT /var/log/cassandra/ "${{targets.destdir}}"/usr/share/java/cassandra/logs

subpackages:
  - name: ${{package.name}}-compat
    dependencies:
      provides:
        - cassandra-compat=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/etc
          ln -sf /opt/cassandra/conf ${{targets.subpkgdir}}/etc/cassandra
          mkdir -p ${{targets.subpkgdir}}/opt
          ln -sf /usr/share/java/cassandra ${{targets.subpkgdir}}/opt/cassandra

  - name: cqlsh-${{vars.major-minor-version}}
    dependencies:
      runtime:
        - python-3.11 # needed for cqlsh
      provides:
        - cqlsh=${{package.full-version}}
    pipeline:
      - runs: |
          set -x
          cython --help
          python3 -m pip install --prefix=/usr --root="${{targets.destdir}}" --requirement ./pylib/requirements.txt 
          python3 -m pip freeze
          # pip freeze does not have a `--root=` arg so here will only list Cython and setuptools
          (cd ./pylib && python setup.py build) # < fo I really need this if we are using pip install now?
          mkdir -p ${{targets.destdir}}/usr/bin
          cp ./bin/cqlsh ${{targets.destdir}}/usr/bin/cqlsh
          cp ./bin/cqlsh.py ${{targets.destdir}}/usr/bin/cqlsh         
          python3 -m pip install --prefix=/usr --root="${{targets.destdir}}" ./pylib
          # `python3 -m pip install` ModuleNotFoundError: No module named 'Cython' error as it is not aware of the 
          # pyt3-cython package installed as an environment dependency
          # (cd ./pylib &&  python setup.py install --prefix=/usr --root="${{targets.destdir}}")
    test:
      environment:
        contents:
          packages:
            - wolfi-base
      pipeline:
        - runs: |
            cqlsh --version

update:
  enabled: true
  github:
    identifier: apache/cassandra
    use-tag: true
    tag-filter-prefix: cassandra-5.0
    strip-prefix: cassandra-

test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: |
        cqlsh --version
