package:
  name: cqlsh-5.0
  version: 5.0.0
  epoch: 0
  description: CQL shell for apache cassandra
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - cqlsh=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cython
      - py3-setuptools
      - python3
      - python3-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 186272edca920c757b91bf95c2392bafa1a38d72
      repository: https://github.com/apache/cassandra
      tag: cassandra-${{package.version}}

  - runs: |
      (cd ./pylib && python setup.py build)

      mkdir -p ${{targets.destdir}}/usr/bin
      cp ./bin/cqlsh ${{targets.destdir}}/usr/bin/cqlsh
      cp ./bin/cqlsh.py ${{targets.destdir}}/usr/bin/cqlsh
      (cd ./pylib &&  python setup.py install --prefix=/usr --root="${{targets.destdir}}")

  - uses: strip

update:
  enabled: true
  github:
    identifier: apache/cassandra
    use-tag: true
    tag-filter-prefix: cassandra-5.0
    strip-prefix: cassandra-